name: Firmware Dump

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: "Accessible ROM URL"
        required: true

defaults:
  run:
    shell: bash

jobs:
  dump:
    runs-on: ubuntu-20.04

    steps:
       - name: Maximize build space
         uses: easimon/maximize-build-space@master
         with:
           remove-dotnet: 'true'
           remove-haskell: 'true'
           remove-codeql: 'true'
           remove-docker-images: 'true'

       - name: Checkouts
         uses: actions/checkout@v3

       - name: Clone Dumprx
         run: |
              git clone https://github.com/DumprX/DumprX

       - name: Setup dumper environment
         working-directory: DumprX
         run: |
              sudo bash setup.sh
              git config --global user.name "Hendra Manudinata"
              git config --global user.email "116422610+manoedinata@users.noreply.github.com"

       - name: Setup config envs
         working-directory: DumprX
         run: |
              echo "manoe-firmware" > .github_orgname
              echo "${{ secrets.FIRMDUMP_CI_TOKEN }}" > .github_token

       - name: Running DumprX
         working-directory: DumprX
         run: |
              ./dumper.sh "${{ github.event.inputs.ROM_URL }}"
